logging:
  level:
    root: info
    sun: error


spring:
  session:
    jdbc:
      initialize-schema: always
  application:
    name: spring-thymeleaf-with-login-2024
  datasource:
    url: jdbc:h2:file:./demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect